import type { ColorSystemOptions } from '@mui/material/styles';
import {
  california,
  forest,
  kepple,
  nevada,
  redOrange,
  royal,
  shakespeare,
  stormGrey,
} from './colors';
import type { ColorScheme } from './types';

export const colorSchemes = {
  dark: {
    palette: {
      action: { disabledBackground: 'rgba(0, 0, 0, 0.12)' },
      background: {
        default: '#0f1410',
        defaultChannel: '15 20 16',
        paper: '#1a2420',
        paperChannel: '26 36 32',
        level1: nevada[800],
        level2: nevada[700],
        level3: nevada[600],
      },
      common: { black: '#000000', white: '#ffffff' },
      divider: 'rgba(255, 255, 255, 0.08)',
      dividerChannel: '255 255 255',
      error: {
        ...redOrange,
        light: redOrange[300],
        main: redOrange[400],
        dark: redOrange[500],
        contrastText: '#000000',
      },
      info: {
        ...shakespeare,
        light: shakespeare[300],
        main: shakespeare[400],
        dark: shakespeare[500],
        contrastText: '#000000',
      },
      neutral: { ...nevada },
      primary: {
        ...forest,
        light: forest[400],
        main: forest[500],
        dark: forest[600],
        contrastText: '#000000',
      },
      secondary: {
        ...royal,
        light: royal[300],
        main: royal[400],
        dark: royal[500],
        contrastText: '#000000',
      },
      success: {
        ...kepple,
        light: kepple[300],
        main: kepple[400],
        dark: kepple[500],
        contrastText: '#000000',
      },
      text: {
        primary: nevada[100],
        primaryChannel: '240 244 248',
        secondary: nevada[400],
        secondaryChannel: '159 166 173',
        disabled: nevada[600],
      },
      warning: {
        ...california,
        light: california[300],
        main: california[400],
        dark: california[500],
        contrastText: '#000000',
      },
    },
  },
  light: {
    palette: {
      action: { disabledBackground: 'rgba(0, 0, 0, 0.06)' },
      background: {
        default: '#ebebeb',
        defaultChannel: '235 235 235',
        paper: '#ffffff',
        level1: '#f0fdf4',
        level2: stormGrey[100],
        level3: stormGrey[200],
      },
      common: { black: '#000000', white: '#ffffff' },
      divider: 'rgba(0, 0, 0, 0.07)',
      dividerChannel: '0 0 0',
      error: {
        ...redOrange,
        light: redOrange[400],
        main: redOrange[500],
        dark: redOrange[600],
        contrastText: '#ffffff',
      },
      info: {
        ...shakespeare,
        light: shakespeare[400],
        main: shakespeare[500],
        dark: shakespeare[600],
        contrastText: '#ffffff',
      },
      neutral: { ...stormGrey },
      primary: {
        ...forest,
        light: forest[400],
        main: forest[600],
        dark: forest[700],
        contrastText: '#ffffff',
      },
      secondary: {
        ...royal,
        light: royal[500],
        main: royal[600],
        dark: royal[700],
        contrastText: '#ffffff',
      },
      success: {
        ...kepple,
        light: kepple[400],
        main: kepple[500],
        dark: kepple[600],
        contrastText: '#ffffff',
      },
      text: {
        primary: stormGrey[900],
        primaryChannel: '33 38 54',
        secondary: stormGrey[500],
        secondaryChannel: '102 112 133',
        disabled: stormGrey[400],
      },
      warning: {
        ...california,
        light: california[400],
        main: california[500],
        dark: california[600],
        contrastText: '#ffffff',
      },
    },
  },
} satisfies Partial<Record<ColorScheme, ColorSystemOptions>>;
